title: Dorae222's BLOG
description: HYU BIZ & BIG DATA
github_username: dorae222
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "dorae222"

baseurl: "https://dorae222.github.io/" 

# Github and twitter are optional:
minima:
  social_links:
    - { platform: github, user_url: "dorae222" }

# Set this to true to get LaTeX math equation support
use_math: 

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: true

# Set this to true to turn on annotations with hypothes.is (https://web.hypothes.is/)
annotations: false

# Set this to true to display tags on each post
show_tags: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: 

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  binder: true
  colab: true
  deepnote: true

# Escape HTML in post descriptions
html_escape:
  description: false

# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /posts/page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# to limit size of xml as it can grow quite large.
feed:
  posts_limit: 5 #default posts_limit: 10
  excerpt_only: true
  
exclude:
  - settings.ini
